apiVersion: apps/v1
kind: Deployment
metadata:
  name: singleuser-deployment
spec:
  replicas: 11
  selector:
    matchLabels:
      component: singleuser-server
  template:
    metadata:
      labels:
        component: singleuser-server
    spec:
      containers:
      - name: singleuser-container
        image: nginx
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            component: singleuser-server
      # - maxSkew: 1
      #   topologyKey: "karpenter.sh/capacity-type"
      #   whenUnsatisfiable: ScheduleAnyway
      #   labelSelector:
      #     matchLabels:
      #       component: singleuser-server
      # nodeSelector:
      #   node.kubernetes.io/instance-type: t3a.xlarge
