apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: x-high-profile
spec:
  template:
    metadata:
      labels:
        profile: x-high
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["r6a.8xlarge"]
      nodeClassRef:
        name: default
  limits:
    cpu: 32
    memory: 256Gi
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h # 30 * 24h = 720h


