apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-shared-data
spec:
  storageClassName: nfs-client
  capacity:
    storage: 400Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /volumes/shared-data
    server: fs-069d2f0d5a2ecb5de.efs.eu-central-1.amazonaws.com
