apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-shared-data
  namespace: datalabs
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 400Gi