apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eiar-datalabs-scio-services
  namespace: datalabs
spec:
  secretName: eiar-datalabs-scio-services-tls
  issuerRef:
    name: letsencrypt-http
    kind: ClusterIssuer  
  commonName: "eiar.datalabs.scio.services"
  dnsNames:
  - "eiar.datalabs.scio.services"
