apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: datalabs-eiar
  namespace: datalabs
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`eiar.datalabs.scio.services`)
      kind: Rule
      services:
        - name: proxy-public
          port: 80
  tls:
    secretName: eiar-datalabs-scio-services-tls
